server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://XX.XX.XX.XX:3100/loki/api/v1/push
    name: loki_client

scrape_configs:
  - job_name: docker-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: docker-logs
          __path__: /var/docker/log/*/*-json.log  # Actual log path
    pipeline_stages:
      - docker: {}
      
  - job_name: npml-access
    static_configs:
      - targets: [localhost]
        labels:
          job: npml-access
          log_type: access
          __path__: /var/npm-local-logs/proxy-host-*_access.log  # Actual log path
    pipeline_stages:
      - regex:
          expression: '^\[(?P<timestamp>[^\]]+)\] - (?P<status>\d+) \d+ - (?P<method>\S+) (?P<scheme>\S+) (?P<domain>[^\s]+) "(?P<path>[^"]+)" \[Client (?P<client_ip>[^\]]+)\] \[Length (?P<length>\d+)\] \[Gzip (?P<gzip>[^\]]+)\] \[Sent-to (?P<backend_ip>[^\]]+)\] "(?P<user_agent>[^"]*)" "(?P<referer>[^"]*)"'
      - labels:
          status:
          method:
          domain:
          scheme:
      - timestamp:
          source: timestamp
          format: "02/Jan/2006:15:04:05 -0700"  # Matches your format